SELECT * FROM BOOK;

-- 리스트가 너무 많아 10개씩 자르는 과정
--1
--SELECT * FROM
--  (SELECT * FROM BOOK ORDER BY BOOKID DESC) SUB;

--2
--SELECT ROWNUM RN, SUB.* FROM 
--    (SELECT * FROM BOOK ORDER BY BOOKID DESC) SUB)

--3 WHERE절이 괄호 안에만 보니까 한번 더 서브쿼리 생성해야 한다.
--SELECT ROWNUM RN, SUB.* FROM 
--    (SELECT * FROM BOOK ORDER BY BOOKID DESC) SUB
--WHERE RN <= 10;

--4 10개씩 보여지기
SELECT * FROM
  (SELECT ROWNUM RN, SUB.* FROM 
    (SELECT * FROM BOOK ORDER BY BOOKID DESC) SUB)
WHERE RN <= 10;

--
SELECT * FROM
  (SELECT ROWNUM RN, SUB.* FROM 
    (SELECT * FROM BOOK ORDER BY BOOKID DESC) SUB)
WHERE RN > ((2-1) * 5) AND RN <= (2 * 5);


