DROP USER scott CASCADE;
CREATE USER scott IDENTIFIED BY tiger DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO scott;
GRANT CREATE VIEW, CREATE SYNONYM TO scott;
GRANT UNLIMITED TABLESPACE TO scott;
ALTER USER scott ACCOUNT UNLOCK;